services:
  - type: web
    name: blueinkhouse-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: "gunicorn blueinkhouse.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
